### PR TITLE
Relax cowlib requirement

### PR DESCRIPTION
**Pull request by nkezhaya**

### CODE REVIEW

**Comment by carrascoacd** [comment]
@polvalente we are facing the same problem if we use the latest version from master.

**Comment by polvalente** [comment]
We can merge this, but I don't know if this fork is relevant anymore. The grpc repo is using the 2.0 rc2 version from hex.pm

**Comment by polvalente** [comment]
Actually, we need to "mix deps.get" here first to also update mix.lock before this is merged

**Comment by carrascoacd** [comment]
Thanks, @polvalente, you are right. Then I think this library is no longer valid for the new version but for the old ones. I think I got confused as the `mix.lock` from our project was pointing to this repository instead.

**Pull request closed without merging**
